# Generated by Django 4.2.1 on 2023-10-29 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0005_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField()),
                ('transaction_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='store.category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='store.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='store.location')),
            ],
        ),
    ]
