# Generated by Django 4.2.1 on 2023-10-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='slug',
        ),
        migrations.AlterField(
            model_name='request',
            name='transaction_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
