# Generated by Django 4.2.1 on 2023-10-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_request_status_alter_request_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
