# Generated by Django 4.2.1 on 2023-11-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank='user', null='user'),
            preserve_default='user',
        ),
    ]
