# Generated by Django 4.2.1 on 2023-11-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_users_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='users',
            name='slug',
        ),
    ]
